const paragraphs = ["aku adalah anak sehat",
                    "ini adalah sebuah paragraf yang cukup panjang dikarenakan dibuat memang supaya panjang karena untuk tes saja jadi bisa dilanjut untuk mengetik jangan sampai fokusmu hilang jika ada huruf yang memang saya buat hilang ataupung berbeda seperti ini adalah kepala dan memiliki raas minas",
                    "Dan kau hadir merubah segalanya, Menjadi lebih indah. Kau bawa cintaku setinggi angkasa; Membuatku merasa sempurnDan membuatku utuh tuk menjalani hidup",
                    "Dalam dunia ini terdapat banyak sekali nama yang unik antaranya: 1.Kliwon, yang bisa dikatan ia adalah anak yang lahir ketika malam kliwon. 2.Uvuvwevwevwe Onyetenyevwe Ugwemuhwem Osas, seorang pria yang pernah membuat heboh dikarenakan namanya yang cukup rumit",
                    "Selain itu, Asep termasuk anak bontot. Anak yang biasanya manja namun: dirinya tidak menyukai'ketika ditanya seperti itu. Seketika asep berteriak 'yare yare daze'",
                    "Bila saatnya t'lah tiba. Kuingin kau menjadi istriku, namun bila saat berpisah t'lah tiba. Diriku pasti akan merasakan suatu kesedihan tiada tara karena t'lah kehilangan dirimu.",
                    "Pada suatu hari dimana aku sedang memetik buah-buahan di Kebun yang kita tanam, Aku menemukan sebuah artifak yang ternyata memiliki kutukan yang sangat kuat: kutukan yang pertaaam adalah kutukan tiga periode dimana jika sudah mendapat dua periode maka tidak bisa menambah periode lagi karena sudah ada peraturannya",
                    "Game viral 'CANDY CRUSH SAGA' yang belakangan ini heboh dikarenakan ada seorang DPR yang memainkannya di sebuah rapat. Padahal jika dalam sebuah rapat tidak diperbolehkan bermain candy crush saga dan juga ketika beliau Beralasan bahwa hanya diletakkan saja maka ITU BUKANLAH CANDY CRUSH SAGA melainkan 'JUDI SLOT GACOR'",
                    "Berjalan-jalan, berjalan-jalan ke pulau, pulau Dewata ku melihat seorang gadis yang wajahnya begitu manis, Yaitu dirimu. Ketika ku mendekati dirimu; Kamu pun tersipu malu'padah tanggal 1 hari rabu malam kamis suro' lebih tepatnya dimana kita bertemu. Sejak saat itu aku terus memikirkanmu ASEP"];
